site_name: Mario Kart DS (EU) documentation
site_description: Mario Kart DS (EU) reverse-enginnering, documented
site_author: XorTroll
site_url: https://xortroll.github.io/mkdsdecomp/

repo_name: mkdsdecomp
repo_url: https://github.com/XorTroll/mkdsdecomp

nav:
  - Home: index.md
  - Game logic: logic.md
  - Navigation: navigation.md
  - File system: fs.md
  - Scenes:
    - Logo: scenes/logo.md
    - Menu2: scenes/menu2.md

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
